"""column in comment table

Revision ID: 941625fa7727
Revises: 4ecff3eccc8e
Create Date: 2024-07-19 05:25:26.423896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941625fa7727'
down_revision = '4ecff3eccc8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_commented', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('date_commented')

    # ### end Alembic commands ###
