"""is_verified in user model for email confirmation

Revision ID: 99694cf07607
Revises: 941625fa7727
Create Date: 2024-07-19 21:16:48.170074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99694cf07607'
down_revision = '941625fa7727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
